# Source: jump-app/charts/jump-app-micros/templates/jump-app/route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: back-golang-test
  namespace: {{ $.Values.app.namespace }}
  labels:
    app.kubernetes.io/id: '{{ $.Values.app.uid }}'
spec:
  to:
    kind: Service
    name: back-golang-v1-test
  port:
    targetPort: http-8442
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None