{{- range $i := untilStep 1 ($.Values.amount | int) 1}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-{{ $i }} 
  namespace: {{ $.Values.argo.namespace }}
  labels:
    app.kubernetes.io/id: '{{ $.Values.uid }}'
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    parameters:
    - name: "app-of-apps.set"
      value: {{ $i }}
    path: .
    repoURL: 'https://github.com/romerobu/app-of-apps' 
    targetRevision: main # branch according to amount of apps per repo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}  