kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin-sa-argo-gitops-test
subjects:
  - kind: ServiceAccount
    name: argocd-argocd-application-controller
    namespace: gitops-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin