---
# Source: deploy-apps-of-apps/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-1 
  namespace: gitops-test
  labels:
    app.kubernetes.io/id: '31466'
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm: 
      parameters:
        - name: amount
          value: "1"       
    path: .
    repoURL: 'https://github.com/romerobu/app-of-apps' 
    targetRevision: main # branch according to amount of apps per repo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# Source: deploy-apps-of-apps/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-2 
  namespace: gitops-test
  labels:
    app.kubernetes.io/id: '31466'
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm: 
      parameters:
        - name: amount
          value: "2"       
    path: .
    repoURL: 'https://github.com/romerobu/app-of-apps' 
    targetRevision: main # branch according to amount of apps per repo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# Source: deploy-apps-of-apps/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-3 
  namespace: gitops-test
  labels:
    app.kubernetes.io/id: '31466'
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm: 
      parameters:
        - name: amount
          value: "3"       
    path: .
    repoURL: 'https://github.com/romerobu/app-of-apps' 
    targetRevision: main # branch according to amount of apps per repo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
