---
# Source: deploy-apps-of-apps/charts/app-of-apps/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-6-1
  namespace: gitops-test
  labels:
    app.kubernetes.io/id: '6774'
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: dev/ocp6/app1
    repoURL: 'https://github.com/romerobu/app-values' # change url and branch to ocp3/app00/...
    targetRevision: main # branch according to amount of apps per repo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# Source: deploy-apps-of-apps/charts/app-of-apps/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-6-2
  namespace: gitops-test
  labels:
    app.kubernetes.io/id: '6774'
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: dev/ocp6/app2
    repoURL: 'https://github.com/romerobu/app-values' # change url and branch to ocp3/app00/...
    targetRevision: main # branch according to amount of apps per repo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# Source: deploy-apps-of-apps/charts/app-of-apps/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-6-3
  namespace: gitops-test
  labels:
    app.kubernetes.io/id: '6774'
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: dev/ocp6/app3
    repoURL: 'https://github.com/romerobu/app-values' # change url and branch to ocp3/app00/...
    targetRevision: main # branch according to amount of apps per repo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
